version: '3'
services:
    mysql:
      image: mysql:5.7.28
      #command: --default-authentication-plugin=mysql_native_password
      container_name: mysql-slave
      restart: always
      hostname: 'db.example.com'
      environment:
        MYSQL_ROOT_PASSWORD: Wchh73****Z4onIZyc  # root账户的密码
      ports:
        - 3308:3306
      volumes:
        - mysql:/var/lib/mysql
        - mysql-conf:/etc/mysql/conf.d
        - /etc/sysconfig/clock:/etc/sysconfig/clock
        - /etc/localtime:/etc/localtime:ro
        - /usr/share/zoneinfo:/usr/share/zoneinfo
      networks:
        - mysql-master-slave
volumes:
    mysql: 
        driver: local
        driver_opts:
            type: bind
            o: bind
            device: ${PWD}/data
    mysql-conf: 
        driver: local
        driver_opts:
            type: bind
            o: bind
            device: ${PWD}/conf/conf.d
networks:
    mysql-master-slave:
      driver: bridge

